### ISSUE TITLE
Bug after use Register()

### ISSUE THREAD

**Issue by felipe-fontes** [JelleDamen/PushwooshMvvmCrossPlugin#2]
After i update mvvm packages. 4.3.0 to 4.4.0
and Xamarin.Android.Support 23.4.0.1 to 24.2.1

11-07 11:34:15.318 16498-16498/com.estrategiamktdigital.foodsage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.estrategiamktdigital.foodsage, PID: 16498
                                                                                   java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                    Caused by: android.runtime.JavaProxyThrowable: MvvmCross.Platform.Exceptions.MvxException: Failed to construct and initialize ViewModel for type Foodsage.Core.ViewModel.ProfileViewModel from locator MvxDefaultViewModelLocator - check InnerException for more information ---> MvvmCross.Platform.Exceptions.MvxException: Problem running viewModel lifecycle of type ProfileViewModel ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
                                                                                     at Foodsage.Core.ViewModel.ProfileViewModel.set_User (Foodsage.Core.Models.User value) [0x00050] in <b038933743db4c22b37ca1c381b27cff>:0 
                                                                                     at Foodsage.Core.ViewModel.ProfileViewModel.Init (Foodsage.Core.ViewModel.Parameters.UserParameter parameter) [0x00017] in <b038933743db4c22b37ca1c381b27cff>:0 
                                                                                       at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
                                                                                     at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <368820a9888f43ddb85d18e87189adbf>:0 
                                                                                      --- End of inner exception stack trace ---
                                                                                     at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00056] in <368820a9888f43ddb85d18e87189adbf>:0 
                                                                                     at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <368820a9888f43ddb85d18e87189adbf>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxViewModelExtensions.CallBundleMethod (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, System.Reflection.MethodInfo methodInfo, MvvmCross.Core.ViewModels.IMvxBundle bundle) [0x0006d] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxViewModelExtensions.CallBundleMethods (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, System.String methodName, MvvmCross.Core.ViewModels.IMvxBundle bundle) [0x00064] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxDefaultViewModelLocator.CallCustomInitMethods (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, MvvmCross.Core.ViewModels.IMvxBundle parameterValues) [0x00000] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxDefaultViewModelLocator.RunViewModelLifecycle (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, MvvmCross.Core.ViewModels.IMvxBundle parameterValues, MvvmCross.Core.ViewModels.IMvxBundle savedState) [0x00000] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                      --- End of inner exception stack trace ---
                                                                                     at MvvmCross.Core.ViewModels.MvxDefaultViewModelLocator.RunViewModelLifecycle (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, MvvmCross.Core.ViewModels.IMvxBundle parameterValues, MvvmCross.Core.ViewModels.IMvxBundle savedState) [0x00039] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxDefaultViewModelLocator.Load (System.Type viewModelType, MvvmCross.Core.ViewModels.IMvxBundle parameterValues, MvvmCross.Core.ViewModels.IMvxBundle savedState) [0x00028] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                     at MvvmCross.Core.ViewModels.MvxViewModelLoader.LoadViewModel (MvvmCross.Core.ViewModels.MvxViewModelRequest request, MvvmCross.Core.ViewModels.IMvxBundle savedState, MvvmCross.Core.ViewModels.IMvxViewModelLocator viewModelLocator) [0x00015] in <69bce0378e8e413982d3b552d7e387a8>:0 
                                                                                      --- End of inner exceptio

**Comment by JelleDamen** [comment]
Hi @Tedyz 
Thanks for reaching out.

Looking at the stacktrace, this error does not seem to be related. You're getting a NullReferenceException when setting the `User` poperty in the `Foodsage.Core.ViewModel.ProfileViewModel`

Please let me know if you found something.

**Comment by JelleDamen** [comment]
will close this issue for now.
